/*
 * CARA Project!
 */
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CaraOption.java
 *
 * Created on 2010-10-31, 11:42:19
 */

package caraswing;

/**
 * Cara Option Window.
 * 
 * @author GUSSET
 * @version 0.1, 10/31/2010
 */
public class CaraOption extends javax.swing.JFrame {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/** Creates new form CaraOption */
	public CaraOption() {
		initComponents();

		// setDefaultCloseOperation
		this.setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jPanelMain = new javax.swing.JPanel();
		jLabelDbDefineDir = new javax.swing.JLabel();
		jTextFieldDbDefineDir = new javax.swing.JTextField();
		jButtonCancel = new javax.swing.JButton();
		jButtonSave = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setName("Form"); // NOI18N
		setResizable(false);

		jPanelMain.setName("jPanelMain"); // NOI18N

		org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application
				.getInstance(caraswing.CaraSwingApp.class).getContext()
				.getResourceMap(CaraOption.class);
		jLabelDbDefineDir.setText(resourceMap
				.getString("jLabelDbDefineDir.text")); // NOI18N
		jLabelDbDefineDir.setName("jLabelDbDefineDir"); // NOI18N

		jTextFieldDbDefineDir.setText(resourceMap
				.getString("jTextFieldDbDefineDir.text")); // NOI18N
		jTextFieldDbDefineDir.setName("jTextFieldDbDefineDir"); // NOI18N

		javax.swing.GroupLayout jPanelMainLayout = new javax.swing.GroupLayout(
				jPanelMain);
		jPanelMain.setLayout(jPanelMainLayout);
		jPanelMainLayout
				.setHorizontalGroup(jPanelMainLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanelMainLayout.createSequentialGroup()
										.addComponent(jLabelDbDefineDir)
										.addContainerGap(231, Short.MAX_VALUE))
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								jPanelMainLayout
										.createSequentialGroup()
										.addContainerGap(73, Short.MAX_VALUE)
										.addComponent(
												jTextFieldDbDefineDir,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												332,
												javax.swing.GroupLayout.PREFERRED_SIZE)));
		jPanelMainLayout.setVerticalGroup(jPanelMainLayout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				jPanelMainLayout.createSequentialGroup().addComponent(
						jLabelDbDefineDir).addPreferredGap(
						javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(jTextFieldDbDefineDir,
								javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(127, Short.MAX_VALUE)));

		jButtonCancel.setText(resourceMap.getString("jButtonCancel.text")); // NOI18N
		jButtonCancel.setName("jButtonCancel"); // NOI18N
		jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButtonCancelActionPerformed(evt);
			}
		});

		jButtonSave.setText(resourceMap.getString("jButtonSave.text")); // NOI18N
		jButtonSave.setName("jButtonSave"); // NOI18N
		jButtonSave.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButtonSaveActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout
				.setHorizontalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																jPanelMain,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE)
														.addGroup(
																javax.swing.GroupLayout.Alignment.TRAILING,
																layout
																		.createSequentialGroup()
																		.addContainerGap(
																				273,
																				Short.MAX_VALUE)
																		.addComponent(
																				jButtonSave)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jButtonCancel)))
										.addContainerGap()));
		layout
				.setVerticalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addContainerGap()
										.addComponent(
												jPanelMain,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												14, Short.MAX_VALUE)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																jButtonCancel)
														.addComponent(
																jButtonSave))
										.addContainerGap()));

		pack();
		// Added for manual initComponents
		initManual();
	}// </editor-fold>//GEN-END:initComponents

	private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonCancelActionPerformed
		// TODO add your handling code here:
		this.setVisible(false);
	}// GEN-LAST:event_jButtonCancelActionPerformed

	private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonSaveActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jButtonSaveActionPerformed

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new CaraOption().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jButtonCancel;
	private javax.swing.JButton jButtonSave;
	private javax.swing.JLabel jLabelDbDefineDir;
	private javax.swing.JPanel jPanelMain;
	private javax.swing.JTextField jTextFieldDbDefineDir;

	// End of variables declaration//GEN-END:variables
 
	/*
	 * Manual Added
	 * <p>
	 * 下面为手动添加。
	 * </p>
	 */
	private void initManual() {
		this.setTitle("Cara Query SQL Parser");
		this.setResizable(false);
	}

}
